#!/usr/bin/env python3
"""Convert ir-ctl pulse/space files into ESP32 Arduino PROGMEM arrays."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_IR_DIR = REPO_ROOT / "ir_codes"
DEFAULT_OUTPUT = REPO_ROOT / "firmware" / "atoms3-agent" / "src" / "ir_timings.h"

HEADER_BANNER = "/* Auto-generated by scripts/ir_to_rmt.py from ir_codes/*.ir — do not edit. */\n"


@dataclass(frozen=True)
class IrSignal:
    filename: str
    carrier_hz: int
    timings: tuple[int, ...]


def c_identifier(filename: str) -> str:
    stem = Path(filename).stem
    ident = re.sub(r"[^0-9A-Za-z_]", "_", stem)
    if ident[0].isdigit():
        ident = f"_{ident}"
    return f"IR_{ident}"


def parse_ir_file(path: Path) -> IrSignal:
    carrier_hz: int | None = None
    timings: list[int] = []
    expecting = "pulse"

    for line_no, raw in enumerate(path.read_text().splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) != 2:
            raise ValueError(f"{path}:{line_no}: expected 'kind value', got {raw!r}")
        kind, value_s = parts
        try:
            value = int(value_s)
        except ValueError as exc:
            raise ValueError(f"{path}:{line_no}: invalid integer {value_s!r}") from exc
        if value < 0:
            raise ValueError(f"{path}:{line_no}: negative timing {value}")

        if kind == "carrier":
            if carrier_hz is not None:
                raise ValueError(f"{path}:{line_no}: duplicate carrier")
            carrier_hz = value
        elif kind == "pulse":
            if expecting != "pulse":
                raise ValueError(f"{path}:{line_no}: expected {expecting}, got pulse")
            timings.append(value)
            expecting = "space"
        elif kind == "space":
            if expecting != "space":
                raise ValueError(f"{path}:{line_no}: expected {expecting}, got space")
            timings.append(value)
            expecting = "pulse"
        elif kind == "timeout":
            continue
        else:
            raise ValueError(f"{path}:{line_no}: unknown token {kind!r}")

    if carrier_hz is None:
        raise ValueError(f"{path}: missing carrier")
    if not timings:
        raise ValueError(f"{path}: no pulse/space timings")
    return IrSignal(filename=path.name, carrier_hz=carrier_hz, timings=tuple(timings))


def load_ir_dir(ir_dir: Path) -> list[IrSignal]:
    files = sorted(ir_dir.glob("*.ir"))
    if not files:
        raise ValueError(f"no .ir files in {ir_dir}")
    return [parse_ir_file(path) for path in files]


def render_header(signals: list[IrSignal]) -> str:
    carriers = {signal.carrier_hz for signal in signals}
    if len(carriers) != 1:
        raise ValueError(f"mixed carrier frequencies: {sorted(carriers)}")
    carrier_hz = next(iter(carriers))
    if carrier_hz % 1000 != 0:
        raise ValueError(f"carrier {carrier_hz} Hz is not a whole kHz")

    lines = [
        HEADER_BANNER,
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
        "struct IrCode {",
        "  const char *filename;",
        "  const uint16_t *timings;",
        "  uint16_t length;",
        "};",
        "",
        f"static const uint8_t IR_CARRIER_KHZ = {carrier_hz // 1000};",
        f"static const uint16_t IR_MAX_TIMINGS = {max(len(s.timings) for s in signals)};",
        "",
    ]

    for signal in signals:
        ident = c_identifier(signal.filename)
        lines.append(f"static const uint16_t {ident}[] PROGMEM = {{")
        row: list[str] = []
        for index, value in enumerate(signal.timings, start=1):
            row.append(str(value))
            if index % 12 == 0:
                lines.append("  " + ", ".join(row) + ",")
                row = []
        if row:
            lines.append("  " + ", ".join(row) + ",")
        lines.append("};")
        lines.append("")

    lines.append("static const IrCode IR_CODES[] = {")
    for signal in signals:
        ident = c_identifier(signal.filename)
        lines.append(f'    {{"{signal.filename}", {ident}, {len(signal.timings)}}},')
    lines.append("};")
    lines.append("")
    lines.append(f"static const size_t IR_CODE_COUNT = {len(signals)};")
    lines.append("")
    return "\n".join(lines)


def write_header(signals: list[IrSignal], output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_header(signals))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ir-dir", type=Path, default=DEFAULT_IR_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)

    signals = load_ir_dir(args.ir_dir)
    write_header(signals, args.output)
    print(f"Wrote {len(signals)} IR codes to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
